# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReplaceWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReplaceWindow(object):
    def setupUi(self, ReplaceWindow):
        ReplaceWindow.setObjectName("ReplaceWindow")
        ReplaceWindow.resize(459, 130)
        self.verticalLayout = QtWidgets.QVBoxLayout(ReplaceWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(ReplaceWindow)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.lineEdit_excel_path = QtWidgets.QLineEdit(ReplaceWindow)
        self.lineEdit_excel_path.setEnabled(False)
        self.lineEdit_excel_path.setText("")
        self.lineEdit_excel_path.setObjectName("lineEdit_excel_path")
        self.horizontalLayout_4.addWidget(self.lineEdit_excel_path)
        self.choseExcelButton = QtWidgets.QPushButton(ReplaceWindow)
        self.choseExcelButton.setObjectName("choseExcelButton")
        self.horizontalLayout_4.addWidget(self.choseExcelButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(ReplaceWindow)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_word_path = QtWidgets.QLineEdit(ReplaceWindow)
        self.lineEdit_word_path.setEnabled(False)
        self.lineEdit_word_path.setText("")
        self.lineEdit_word_path.setObjectName("lineEdit_word_path")
        self.horizontalLayout_3.addWidget(self.lineEdit_word_path)
        self.choseWrodButton = QtWidgets.QPushButton(ReplaceWindow)
        self.choseWrodButton.setObjectName("choseWrodButton")
        self.horizontalLayout_3.addWidget(self.choseWrodButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(ReplaceWindow)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.lineEdit_output_name = QtWidgets.QLineEdit(ReplaceWindow)
        self.lineEdit_output_name.setEnabled(True)
        self.lineEdit_output_name.setText("")
        self.lineEdit_output_name.setObjectName("lineEdit_output_name")
        self.horizontalLayout_5.addWidget(self.lineEdit_output_name)
        self.replaceButton = QtWidgets.QPushButton(ReplaceWindow)
        self.replaceButton.setObjectName("replaceButton")
        self.horizontalLayout_5.addWidget(self.replaceButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(ReplaceWindow)
        QtCore.QMetaObject.connectSlotsByName(ReplaceWindow)

    def retranslateUi(self, ReplaceWindow):
        _translate = QtCore.QCoreApplication.translate
        ReplaceWindow.setWindowTitle(_translate("ReplaceWindow", "EXCEL->Word 内容替换"))
        self.label.setText(_translate("ReplaceWindow", "Excel路径："))
        self.choseExcelButton.setText(_translate("ReplaceWindow", "选择Excel数据文件"))
        self.label_2.setText(_translate("ReplaceWindow", "Word路径："))
        self.choseWrodButton.setText(_translate("ReplaceWindow", "选择Word模板文件"))
        self.label_3.setText(_translate("ReplaceWindow", "批量生成文件名："))
        self.lineEdit_output_name.setPlaceholderText(_translate("ReplaceWindow", "按字段标题替换，默认保留模板名称"))
        self.replaceButton.setText(_translate("ReplaceWindow", "替换"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReplaceWindow = QtWidgets.QDialog()
    ui = Ui_ReplaceWindow()
    ui.setupUi(ReplaceWindow)
    ReplaceWindow.show()
    sys.exit(app.exec_())
